NEPI_HW: JETSON
NEPI_PYTHON: 3.8
NEPI_IN_CONTAINER: 0
NEPI_HAS_CUDA: 1
NEPI_HAS_XPU: 0
NEPI_MANAGES_SSH: 1
NEPI_MANAGES_SHARE: 1
NEPI_MANAGES_TIME: 0
NEPI_MAGAGES_NETWORK: 0
NEPI_IP: 192.168.179.103
NEPI_USER: nepi
NEPI_DOCKER: /mnt/nepi_docker
NEPI_STORAGE: /mnt/nepi_storage
NEPI_CONFIG: /mnt/nepi_config
NEPI_HOME: /home/nepi
NEPI_BASE: /opt/nepi
NEPI_RUI: /opt/nepi/nepi_rui
NEPI_ENGINE: /opt/nepi/nepi_engine
NEPI_ETC: /opt/nepi/etc
NEPI_SCRIPTS: /opt/nepi/scripts
NEPI_USR_CONFIG: /mnt/nepi_storage/user_cfg
NEPI_DOCKER_CONFIG: /mnt/nepi_config/docker_config
NEPI_FACTORY_CONFIG: /mnt/nepi_config/factory_cfg
NEPI_SYSTEM_CONFIG: /mnt/nepi_config/system_cfg
NEPI_CODE: /mnt/nepi_storage/code
NEPI_ALIASES_FILE: .nepi_system_aliases
NEPI_AB_FS: 1
