#!/bin/bash

##
## Copyright (c) 2024 Numurus, LLC <https://www.numurus.com>.
##
## This file is part of nepi-engine
## (see https://github.com/nepi-engine).
##
## License: 3-clause BSD, see https://opensource.org/licenses/BSD-3-Clause
##

# This file contains nepi docker host system aliases and sources nepi bash utils

#echo "########################"
#echo "NEPI Docker Aliases"
#echo "########################"

export NEPI_CONFIG=${HOME}/.NEPI_CONFIG
source ${NEPI_CONFIG}


NEPI_UTILS_FILE=/home/${USER}/.nepi_bash_utils
source $NEPI_UTILS_FILE
UINFO="$(. ${NEPI_UTILS_FILE} && utilsn)"

########################
# Help Msg Initialization
#########################
HELPN=${UINFO}


#############################
# NEPI DOCKER FUNCTIONS
#############################


function create_tag(){
    refresh_nepi_config 
    wait
    SW_VERSION=$1
    HW_TYPE=$2
    HW_MODEL=$3
    
    TAG_VARIABLE=$4
    tag=${SW_VERSION}-${HW_TYPE}-${HW_MODEL}
    export TAG_VARIABLE="${tag,,}" # Convert to lowercase
    echo "$TAG_VARIABLE"
}
export -f create_tag

######################
# UPDATE NEPI DOCKER CONFIG
######################
function config_nepi(){
    #Run NEPI Docker Config Script
    . /home/${USER}/docker_config_setup.sh
}
export -f config_nepi

######################
# RUN_NEPI
######################
function run_nepi(){
    #Run NEPI in Normal Mode
    export IT_MODE=0
    export REMOVE_MODE=1
    . ${NEPI_DOCKER_CONFIG}/start_nepi_docker.sh
}
export -f run_nepi



######################
# COMMIT_NEPI
######################
function commit_nepi(){
    # Commit the Running Container
    if [[ ! -v NEPI_RUNNING ]]; then
        if [[ ( -v NEPI_RUNNING && "$NEPI_RUNNING" -eq 1 ) ]]; then
            echo "Stopping Running NEPI Docker Process ${NEPI_RUNNING_NAME}:${NEPI_RUNNING_TAG} ID:${NEPI_RUNNING_ID}"
            dcommit $NEPI_RUNNING_ID ${1}:${2}
        else
            echo "No Running NEPI Contatainer to Commit"
        fi
    else
        echo "Failed to Read NEPI Docker Config File"
        exit 1
    fi 
}
export -f commit_nepi

######################
# LOGIN_NEPI
######################
function login_nepi(){
  . ${NEPI_DOCKER_CONFIG}/docker_cfg/nepi_docker_login.sh   
}
export -f login_nepi

######################
# SWITCH_NEPI
######################
function switch_nepi(){
  . ${NEPI_DOCKER_CONFIG}/nepi_docker_switch.sh
}
export -f switch_nepi

######################
# IMPORT_NEPI
######################

function import_nepi(){
  . ${NEPI_DOCKER_CONFIG}/nepi_docker_import.sh
}
export -f import_nepi

######################
# EXPORT_NEPI
######################

function export_nepi(){
  . ${NEPI_DOCKER_CONFIG}/nepi_docker_export.sh
}
export -f ffile




###################################
# NEPI SSH Agent Config
###################################

CURRENT_DIR=$(pwd)

export NEPI_SSH_KEY_PATH=~/ssh_keys/nepi_engine_default_private_ssh_key

LOCALHOST_IP="127.0.0.1"
export NEPI_TARGET_IP=$LOCALHOST_IP
export NEPI_TARGET_USERNAME=$NEPI_USER
export NEPI_SSH_KEY=~/ssh_keys/nepi_engine_default_private_ssh_key
export NEPI_TARGET_SRC_DIR=${NEPI_STORAGE}/nepi_src # This is the default if unset

# Setup Connection Shortcuts
alias sshn="ssh -o StrictHostKeyChecking=no -i $NEPI_SSH_KEY_PATH nepi@nepi"
alias scpn="scp -o StrictHostKeyChecking=no -i $NEPI_SSH_KEY_PATH nepi@nepi"
alias sftpn="sftp -o StrictHostKeyChecking=no -i $NEPI_SSH_KEY_PATH nepi@nepi"


SSH_ENV="$HOME/.ssh/environment"

function run_ssh_env {
  . "${SSH_ENV}" > /dev/null
}

function start_ssh_agent {
  echo "Initializing new SSH agent..."
  ssh-agent | sed 's/^echo/#echo/' > "${SSH_ENV}"
  echo "succeeded"
  chmod 600 "${SSH_ENV}"

  run_ssh_env;

  ssh-add ~/.ssh/id_rsa;
}

if [ -f "${SSH_ENV}" ]; then
  run_ssh_env;
  ps -ef | grep ${SSH_AGENT_PID} | grep ssh-agent$ > /dev/null || {
    start_ssh_agent;
  }
else
  start_ssh_agent;
fi



###################################
###################################
#NEPI folder shortcuts
export AI="/mnt/nepi_storage/ai_models"
export AIF="/opt/nepi/nepi_engine/share/nepi_ai_ifs"
export API="/opt/nepi/nepi_engine/lib/python3/dist-packages/nepi_api"
export APPS="/opt/nepi/nepi_engine/share/nepi_apps"
export AUTO="/mnt/nepi_storage/automation_scripts"
export DATA="/mnt/nepi_storage/data"
export DIST="/opt/nepi/nepi_engine/lib/python3/dist-packages"
export DRIVERS="/opt/nepi/nepi_engine/lib/nepi_drivers"
export ENGINE="/opt/nepi/nepi_engine"
export ETC="/opt/nepi/nepi_engine/etc"
export INSTALL="/mnt/nepi_storage/intstall"
export LAUNCH="/opt/nepi/nepi_engine/share/nepi_env/launch"
export LIB="/opt/nepi/nepi_engine/lib"
export LIBSDK="/opt/nepi/nepi_engine/lib/nepi_sdk"
export MANAGERS="/opt/nepi/nepi_engine/lib/nepi_managers"
export NEPI="/opt/nepi"
export NFI="/mnt/nepi_storage/nepi_full_img"
export NFIA="/mnt/nepi_storage/nepi_full_img_archive"
export RUI="/opt/nepi/nepi_rui/src/rui_webserver/rui-app/src"
export RUI_ENV="/opt/nepi/nepi_rui"
export SDK="/opt/nepi/nepi_engine/lib/python3/dist-packages/nepi_sdk"

export SHARE="/opt/nepi/nepi_engine/share"
export SRC="/mnt/nepi_storage/nepi_src/nepi_engine_ws/src"
export SRCRUI="/mnt/nepi_storage/nepi_src/nepi_engine_ws/src/nepi_rui/src/rui_webserver/rui-app/src"
export TMP="/mnt/nepi_storage/tmp"
export DRIVE="/mnt/nepi_storage"



#NEPI sftp folder shortcuts
# Function to open sftp to location on nepi device
# Example call: sftpnl '/mnt/nepi_storage'
function sftpnl(){
sftp -o StrictHostKeyChecking=no -i $NEPI_SSH_KEY_PATH nepi@nepi:../.."$@"
}
function ai(){
	sftpnl $AI
}	
function aifs(){
	sftpnl $AIFS
}	
function api(){
	sftpnl $API
}	
function apps(){
	sftpnl $APPS
}
function auto(){
	sftpnl $AUTO
}
function data(){
	sftpnl $DATA
}	
function dist(){
	sftpnl $DIST
}	
function drivers(){
	sftpnl $DRIVERS
}	
function engine(){
	sftpnl $ENGINE
}
function etc(){
	sftpnl $ETC
}	
function intstall(){
	sftpnl $INSTALL
}	
function lib(){
	sftpnl $LIB
}	
function libsdk(){
	sftpnl $LIBSDK
}	
function managers(){
	sftpnl $MANAGERS
}	
function nepi(){
	sftpnl $NEPI
}	
function nfi(){
	sftpnl $NFI
}	
function nfia(){
	sftpnl $NFIA
}	
function rui(){
	sftpnl $RUI
}
function rui_env(){
	sftpnl $RUI_ENV
}	
function sdk(){
	sftpnl $SDK
}	
function share(){
	sftpnl $SHARE
}	
function src(){
	sftpnl $SRC
}	
function srcrui(){
	sftpnl $SRCRUI
}
function tmp(){
	sftpnl $TMP
}	
function drive(){
	sftpnl $DRIVE
}


export FCFG="/mnt/nepi_config/factory_cfg"
export SCFG="/mnt/nepi_config/system_cfg"
export UCFG="/mnt/nepi_storage/user_cfg"

function fcfg(){
	sftpnl $FCFG
}	

function scfg(){
	sftpnl $SCFG
}	

function ucfg(){
	sftpnl $UCFG
}	

HELPN="${HELPN}
################################
## NEPI sftp folder shortcuts ##
################################
drive = /mnt/nepi_storage
ai = /mnt/nepi_storage/ai_models
aifs = /opt/nepi/nepi_engine/share/nepi_aifs
api = /opt/nepi/nepi_engine/lib/python3/dist-packages/nepi_api
apps = /opt/nepi/nepi_engine/share/nepi_apps
auto = /mnt/nepi_storage/automation_scripts
data = /mnt/nepi_storage/data
dist = /opt/nepi/nepi_engine/lib/python3/dist-packages/
drivers = /opt/nepi/nepi_engine/lib/nepi_drivers
engine = /opt/nepi/nepi_engine
etc = /opt/nepi/nepi_engine/etc
intstall = /mnt/nepi_storage/intstall
lib = /opt/nepi/nepi_engine/lib
libsdk = /opt/nepi/nepi_engine/lib/sdk
managers = /opt/nepi/nepi_engine/lib/nepi_managers
nepi = /opt/nepi
nfi = /mnt/nepi_storage/nepi_full_img
nfia = /mnt/nepi_storage/nepi_full_img_archive
rui = /opt/nepi/rui/src/rui_webserver/rui-app/src
rui_env = /opt/nepi/rui
sdk = /opt/nepi/nepi_engine/lib/python3/dist-packages/nepi_sdk
share = /opt/nepi/nepi_engine/share
src = /mnt/nepi_storage/nepi_src/nepi_engine_ws/src
srcrui = /mnt/nepi_storage/nepi_src/nepi_engine_ws/src/nepi_rui/src/rui_webserver/rui-app/src
tmp = /mnt/nepi_storage/tmp
fcfg = /mnt/nepi_config/factory_cfg
scfg = /mnt/nepi_config/system_cfg
ucfg = /mnt/nepi_storage/user_cfg"

export SETUPN="${USER}/nepi_engine_ws/setup"
alias setupn="cd ${SETUPN}"

HELPN="${HELPN}
################################
## NEPI folder shortcuts ##
################################
setupn = ${USER}/nepi_engine_ws/setup"


function helpn(){
    echo "$HELPN"
}

export NEPI_REMOTE_SETUP=0
export NEPI_TARGET_SRC_DIR=${NEPI_STORAGE}/nepi_src


