#!/bin/bash

##
## Copyright (c) 2024 Numurus, LLC <https://www.numurus.com>.
##
## This file is part of nepi-engine
## (see https://github.com/nepi-engine).
##
## License: 3-clause BSD, see https://opensource.org/licenses/BSD-3-Clause
##


# This file contains nepi bash utility functions

#echo "########################"
#echo "STARTING NEPI Bash Utils"
#echo "########################"


utilsn="#############################
## NEPI Util Functions ##
#############################"


###################################
# System Util Functions
###################################

# echo variable value
function echovar(){
    local var_name="$1"
    echo "$var_name: ${!var_name}"
}
export -f echovar

# ping internet
function pingi(){
    if ! ping -c 2 google.com; then
        echo "No Internet Connection"
        return 0
    else
        echo "Internet Connected"
        return 1
    fi
}
export -f pingi

# ping nepi
function pingn(){
  ping ${NEPI_IP}
}
export -f pingn

# source bashrc
function sbrc(){
    source /home/${USER}/.bashrc
}
export -f sbrc

function sdhcp(){
    sudo dhclient -r
    sudo dhclient
    sudo dhclient -nw
}
export -f sdhcp

utilsn="${utilsn}
### SYSTEM UTIL FUNCTIONS
pingi = Check for internet
sbrc = Source the current users bashrc file
sdhcp = Start DHCP Internet Client"


###################################
# File Util Functions
###################################

# Function to search for text
# Example call: find 'nepi_sdk.parse_header_msg'
function ftext(){
grep -r "$@" ./*
}
export -f ftext

# Function to search for text
# Example call: find 'nepi_sdk.parse_header_msg'
function ffile(){
find ./* -iname  "*$@*" 
}
export -f ffile

function update_text_value(){
  KEY=$2
  UPDATE=$3
  FILE=$1
  if [ -f "$FILE" ]; then
    if grep -q "$KEY" "$FILE"; then
      sed -i "/^$KEY/c\\$UPDATE" "$FILE"
    else
      echo "$UPDATE" | sudo tee -a $FILE
    fi
  else
    echo "File not found ${FILE}"
  fi
}
export -f update_text_value


function update_yaml_value(){
    KEY=$1
    #echo $KEY
    VAL=$2
    #echo $VAL
    FILE=$3
    #echo $FILE
    yq e -i '.'"$KEY"' = env(VAL)' $FILE
}
export -f update_yaml_value

function export_yaml_value(){
    KEY=$1
    #echo $KEY
    VARIABLE=$2
    #echo=$VARIABLE
    FILE=$3
    #echo=$FILE
    verbose=0
    value=$(yq e '.'"$KEY"'' $FILE)
    export ${VARIABLE}=$value
    #Secho "${VARIABLE}=${value}"
}
export -f export_yaml_value

function load_config_file(){
    config_file=$1
    echo $config_file
    if [ -f "$config_file" ]; then
        keys=($(yq e 'keys | .[]' ${config_file}))
        for key in "${keys[@]}"; do
            export_yaml_value "${key}" "${key}" "$config_file" 
        done
    else
        echo "Config file not found ${config_file}"
    fi
}

export -f load_config_file

function print_config_file(){
    echo $1
    config_file=${1}
    if [ -f "$config_file" ]; then
        CONFIGN="#############################
        ## NEPI Config Settings ##
        #############################
        FILE=${config_file}"

        keys=($(yq e 'keys | .[]' ${config_file}))
        for key in "${keys[@]}"; do
            value=$(yq e '.'"$key"'' $config_file)
            echo "${key}=${value}"
            CONFIGN="${CONFIGN}
            ${key}=${!key}"
        done
        echo $CONFIG
    else
        echo "Config file not found ${config_file}"
    fi
}

export -f print_config_file

#### Update Help Test
utilsn="${utilsn}
### NEPI FILE UTIL FUNCTIONS
ftext = Find text in files recursively
ffile = Find filenames with text match recursively
update_text_value = Adds or Replaces value in text file given FILE KEY UPDATE_STRING FILE
update_yaml_value = Update entry in yaml file given KEY VAL FILE
export_yaml_value = Exports the value of yaml entry to system variable given KEY VARIBLE FILE
load_config_file = Exports all of the yaml entries to system variables given FILE"



###################################
# Git Util Functions
###################################

function gitn(){
  PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\033[0;32m$(__git_ps1 " (%s)")\033[0m\$ '
}

function pushn(){
git add --all
git commit -m "*$@*" 
git push
}



utilsn="${utilsn}
### Git UTIL FUNCTIONS
gitn = adds git repo info to terminal prompt
pushn = Add,commit,push repo changes with provided comment"




###################################
# Docker Util Functions
###################################

if which docker &> /dev/null; then
  function dimg(){
    sudo docker images
  }

  function dps(){
    sudo docker ps -a
  }

  
utilsn="${utilsn}
### Docker UTIL FUNCTIONS
dimg = sudo docker images
dps = sudo docker ps -a"

fi



###################################
# ROS Util Functions
###################################
NROS=/opt/nepi/nepi_engine/setup.bash
ROS=/opt/ros/noetic/setup.bash
HAS_ROS=$(dpkg -l | grep ros-)
if [ 1 ]; then # [[ -z "$HAS_ROS" ]]; then

    NEEDS_ROS=1

    # Function to search for topic containing string
    function sros(){
      # Source ROS Env
      if [[ -f "$NROS" ]]; then
        source $NROS
      elif [[ -f "$ROS" ]]; then
        source /opt/ros/noetic/setup.bash
      else
        echo "No Ros Setup File Found"
      fi
      NEEDS_ROS=0
    }

    export -f sros



    # Function to search for topic containing string
    function ftopic(){
    if [ "$NEEDS_ROS" -eq 1 ]; then
      sros
      wait
      NEEDS_ROS=0
    fi
    rostopic list | grep "$@" 
    }

    # Function to print all topics out
    function ltopics(){
    if [ "$NEEDS_ROS" -eq 1 ]; then
      sleep 1 & sros
      wait
      NEEDS_ROS=0
    fi
    rostopic list
    }

    # Function to listen to topic
    function etopic(){
    if [ "$NEEDS_ROS" -eq 1 ]; then
      sleep 1 & sros
      wait
      NEEDS_ROS=0
    fi
    rostopic echo "$@" 
    }

    # Function to search for service containing string
    function fservice(){
    if [ "$NEEDS_ROS" -eq 1 ]; then
      sleep 1 & sros
      wait
      NEEDS_ROS=0
    fi
    rosservice list | grep "$@" 
    }

    # Function to print all services out
    function lservices(){
    if [ "$NEEDS_ROS" -eq 1 ]; then
      sleep 1 & sros
      wait
      NEEDS_ROS=0
    fi
    rosservice list
    }

    # to call service
    function cservice(){
    if [ "$NEEDS_ROS" -eq 1 ]; then
      sleep 1 & sros
      wait
      NEEDS_ROS=0
    fi
    rosservice call "$@"
    }

utilsn="${utilsn}
### ROS UTIL FUNCTIONS
sros = source ros bash setup
ltopics = List all active topics
ftopic = Find topics containing provided string
etopic = Echo to provided topic
lservices = List all active services
fservice = Find services containing provided string
cservice = Call service"

fi


###################################
# NEPI DEV Util Functions
###################################


  function nepiclone(){
  if [ ! -d "${HOME}/nepi_engine_ws" ]; then
    sudo mkdir $NEPI_SOURCE
    sudo chmod -R ${USER}:${USER} $NEPI_SOURCE
  fi
  if [ -d "${HOME}/nepi_engine_ws" ]; then
    if [ -d "${SOURCE_FOLDER}" ]; then
      echo "NEPI Source Folder Exists: ${SOURCE_FOLDER}. Delete and try again"
    else
      cd ${HOME}/nepi_engine_ws
      BRANCH=main
      if [[ "$NEPI_ROS" == "NOETIC" ]]; then
        SUBBRANCH=ros1_main
      else
        SUBBRANCH=ros2_main
      fi
      git clone git@github.com:nepi-engine/nepi_engine_ws.git
      cd nepi_engine_ws
      git checkout $BRANCH
      git submodule update --init --recursive
      git submodule update 
      git submodule foreach git checkout $SUBBRANCH 
      git submodule foreach git pull origin $SUBBRANCH
    fi
  fi
  }

  function nepiclonedev(){
  if [ ! -d "${HOME}/nepi_engine_ws" ]; then
    sudo mkdir $NEPI_SOURCE
    sudo chmod -R ${USER}:${USER} $NEPI_SOURCE
  fi
  if [ -d "${HOME}/nepi_engine_ws" ]; then
    if [ -d "${SOURCE_FOLDER}" ]; then
      echo "NEPI Source Folder Exists: ${SOURCE_FOLDER}. Delete and try again"
    else
      cd ${HOME}/nepi_engine_ws
      if [[ "$NEPI_ROS" == "NOETIC" ]]; then
        BRANCH=ros1_develop
        SUBBRANCH=ros1_main
      else
        BRANCH=ros2_develop
        SUBBRANCH=ros2_main
      fi
      git clone git@github.com:nepi-engine/nepi_engine_ws.git
      cd nepi_engine_ws
      git checkout $BRANCH
      git submodule update --init --recursive
      git submodule update 
      git submodule foreach git checkout $SUBBRANCH
      git submodule foreach git pull origin $SUBBRANCH
    fi
  fi
  }


  ## NEPI deploy complete
  alias nepidpl="
  cd $SOURCE_FOLDER
  ./deploy_nepi_complete.sh"

  # NEPI deploy repos
  alias repodpl="
  cd $SOURCE_FOLDER
  ./deploy_nepi_repos.sh"

utilsn="${utilsn}
### NEPI DEV UTIL FUNCTIONS
nepiclone = clone nepi main repo
nepiclonedev = clone nepi dev repo
nepidpl = deploy nepi complete
repodpl = deploy specific repos"

###################################
# NEPI SYSTEM Util Functions
###################################

if [ 1 ]; then

  # NEPI stop and start shortcuts
  function nepistop(){
    if [[ "$NEPI_IN_CONTAINER" -eq 1 ]]; then
      sudo supervisorctl stop nepi_engine
    else
      sudo systemctl stop nepi_engine
    fi
  }

  function nepistart(){
    if [[ "$NEPI_IN_CONTAINER" -eq 1 ]]; then
      sudo ${NEPI_ENGINE}/etc/nepi_env/nepi_launch.sh
    else
      sudo ${NEPI_ENGINE}/etc/nepi_env/nepi_launch.sh
    fi
  }

  # copy arvhived images to install folder
  function mvimg(){
      nimg=$NEPI_IMPORT_PATH
      narch=$NEPI_EXPORT_PATH
      if [[ "$nimg" != "$narch" ]]; then
        mv ${narch}/* $nimg/
      fi
  }

  # copy arvhived images to install folder
  function ndhcp(){
      if [[ -f "/opt/nepi/scripts/nepi_dhcp_start" ]]; then
        export ENABLE_NEPI_DHCP=1
        source /opt/nepi/scripts/nepi_dhcp_start
      fi
  }

  function snvm(){
    echo ' ' | sudo tee -a $BASHRC
    echo '##### NVM Config #####' | sudo tee -a $BASHRC
    echo 'export NVM_DIR='/home/${NEPI_USER}'/.nvm' | sudo tee -a $BASHRC
    echo '[ -s ${NVM_DIR}/nvm.sh ] && \. ${NVM_DIR}/nvm.sh' | sudo tee -a $BASHRC
    echo '[ -s ${NVM_DIR}/bash_completion ] && \. ${NVM_DIR}/bash_completion' | sudo tee -a $BASHRC
  }

  BUILD=${NEPI_STORAGE}/nepi_src/nepi_engine_ws
  ## NEPI build shortcuts
  alias nepibld="
  cd $BUILD
  ./build_nepi_complete.sh"

  # NEPI build shortcuts
  alias codebld="
  cd $BUILD
  ./build_nepi_code.sh"

  # NEPI build shortcuts
  alias ruibld="
  cd $BUILD
  ./build_nepi_rui.sh"





utilsn="${utilsn}
### NEPI SYSTEM UTIL FUNCTIONS
nepistart = start the nepi processes
nepistop = stop the nepi processe
mvimg = Move archived nepi images to nepi image install folder
snvm = Sources NVM (Node Version Manager) nmv.sh
nepibld = build/deploy all nepi repos and RUI
codebld = build/deploy all nepi repos
ruibld = build/deploy rui system"
fi


export UTILSN=${utilsn}

export NEPI_UTILS_SOURCED=1


