#!/bin/bash

##
## Copyright (c) 2024 Numurus, LLC <https://www.numurus.com>.
##
## This file is part of nepi-engine
## (see https://github.com/nepi-engine).
##
## License: 3-clause BSD, see https://opensource.org/licenses/BSD-3-Clause
##


# This file contains nepi docker host system aliases and sources nepi bash utils
HELPN="
#############################
## NEPI Help Info ##
#############################"

########################
# Variable Initailization
#########################

# HW OPTIONS [JETSON,ARM,AMD,RPI]
export NEPI_HW=JETSON

arch_hw=arm64
if [ "$NEPI_HW" == "JETSON" ]; then
  arch_hw=arm64
fi
if [ "$NEPI_HW" == "ARM" ]; then
  arch_hw=arm64
fi
if [ "$NEPI_HW" == "AMD" ]; then
  arch_hw=amd64
fi
if [ "$NEPI_HW" == "RPI" ]; then
  arch_hw=rpi
fi
export NEPI_ARCH=$arch_hw

# NEED TO: Set to $NEPI_DOCKER_CONFIG_PATH from ???
export NEPI_DOCKER_CONFIG_FOLDER=/mnt/nepi_config/docker_config
export NEPI_DOCKER_CONFIG_FILE=${NEPI_DOCKER_CONFIG_FOLDER}/nepi_docker_config.yaml
export NEPI_DOCKER_COMPOSE_FILE=${NEPI_DOCKER_CONFIG_FOLDER}/nepi_docker_compose.yml

## NEED TO: Read these from nepi_config.yaml file
export ACTIVE_CONT=nepi_fs_a
export ACTIVE_VERSION=3p2p0-RC2
export ACTIVE_TAG=jetson-3p2p0-rc2
export ACTIVE_ID=0

export INACTIVE_CONT=nepi_fs_b
export INACTIVE_VERSION=uknown
export INACTIVE_TAG=jetson-uknown
export INACTIVE_ID=0

export STAGING_CONT=nepi_staging

export IMPORT_PATH=/media/nepidev/NServer_Backup
export EXPORT_PATH=/mnt/nepi_storage/nepi_full_img_archive

######  NEED TO: Update from current docker status
export RUNNING_CONT=None
export RUNNING_VERSION=uknown
export RUNNING_TAG=uknown
export RUNNING_ID=0

export NEPI_REMOTE_SETUP=1

#### Update Help Test
HELPN="${HELPN}

### NEPI DOCKER CONFIG

NEPI_HW=${NEPI_HW}
NEPI_ARCH=${NEPI_ARCH}
NEPI_DOCKER_CONFIG_FOLDER=${NEPI_DOCKER_CONFIG_FOLDER}
NEPI_DOCKER_CONFIG_FILE=${NEPI_DOCKER_CONFIG_FILE}
NEPI_DOCKER_COMPOSE_FILE=${NEPI_DOCKER_COMPOSE_FILE}

ACTIVE_CONT=${ACTIVE_CONT}
ACTIVE_VERSION-eq${ACTIVE_VERSION}
ACTIVE_TAG=${ACTIVE_TAG}
ACTIVE_ID=${ACTIVE_ID}

INACTIVE_CONT=${INACTIVE_CONT}
INACTIVE_VERSION=${INACTIVE_VERSION}
INACTIVE_TAG=${INACTIVE_TAG}
INACTIVE_ID=${INACTIVE_ID}

STAGING_CONT=${STAGING_CONT}
IMPORT_PATH=${IMPORT_PATH}
EXPORT_PATH=${EXPORT_PATH}

RUNNING_CONT=${RUNNING_CONT}
RUNNING_VERSION=${RUNNING_VERSION}
RUNNING_TAG=${RUNNING_TAG}
RUNNING_ID=${RUNNING_ID}"


###################################
###################################
#NEPI folder shortcuts
export DRIVE="/mnt/nepi_storage"

export AI="/mnt/nepi_storage/ai_models"
export AUTO="/mnt/nepi_storage/automation_scripts"
export DATA="/mnt/nepi_storage/data"
export INSTALL="/mnt/nepi_storage/intstall"
export NFI="/mnt/nepi_storage/nepi_full_img"
export NFIA="/mnt/nepi_storage/nepi_full_img_archive"
export SRC="/mnt/nepi_storage/nepi_src/nepi_engine_ws/src"
export SRCRUI="/mnt/nepi_storage/nepi_src/nepi_engine_ws/src/nepi_rui/src/rui_webserver/rui-app/src"
export TMP="/mnt/nepi_storage/tmp"

export FCFG="/mnt/nepi_config/factory_cfg"
export SCFG="/mnt/nepi_config/system_cfg"
export UCFG="/mnt/nepi_storage/user_cfg"

# NEPI navigation shortcuts
alias drive="cd $DRIVE"

alias ai="cd $AI"
alias aif="cd $AIF"
alias auto="cd $AUTO"
alias data="cd $DATA"
alias intstall="cd $INSTALL"
alias nfi="cd $NFI"
alias nfia="cd $NFIA"
alias src="cd $SRC"
alias srcrui="cd $SRCRUI"
alias tmp="cd $TMP"
alias train="cd $TRAIN"


alias fcfg="cd $FCFG"
alias scfg="cd $SCFG"
alias ucfg="cd $UCFG"

### SOURCE NEPI UTIL FUNCTIONS
NUSH=${HOME}/.nepi_bash_utils
#echo "Sourcing ${NUSH}"
sleep 1 & source $NUSH
wait
# Print out nepi aliases
UINFO="$(. ${NUSH} && utilsn)"
#echo "${UINFO}"
# Print out the nepi shortcuts
function helpn(){
    HELPN="${HELPN}

${UINFO}

################################
## NEPI folder shortcuts ##
################################
drive = /mnt/nepi_storage

ai = /mnt/nepi_storage/ai_models
auto = /mnt/nepi_storage/automation_scripts
data = /mnt/nepi_storage/data
intstall = /mnt/nepi_storage/intstall
nfi = /mnt/nepi_storage/nepi_full_img
nfia = /mnt/nepi_storage/nepi_full_img_archive
src = /mnt/nepi_storage/nepi_src/nepi_engine_ws/src
srcrui = /mnt/nepi_storage/nepi_src/nepi_engine_ws/src/nepi_rui/src/rui_webserver/rui-app/src
tmp = /mnt/nepi_storage/tmp

fcfg = /mnt/nepi_config/factory_cfg
scfg = /mnt/nepi_config/system_cfg
ucfg = /mnt/nepi_storage/user_cfg
"
    echo "$HELPN"
}



