#!/bin/bash

##
## Copyright (c) 2024 Numurus, LLC <https://www.numurus.com>.
##
## This file is part of nepi-engine
## (see https://github.com/nepi-engine).
##
## License: 3-clause BSD, see https://opensource.org/licenses/BSD-3-Clause
##

NUSH=${HOME}/.nepi_bash_utils
source $NUSH
UINFO="$(. ${NUSH} && utilsn)"


# This file contains nepi docker host system aliases and sources nepi bash utils
HELPN="
#############################
## NEPI Help Info ##
#############################"

########################
# Variable Initailization
#########################

# HW OPTIONS [JETSON,ARM,AMD,RPI]
export NEPI_HW=JETSON

arch_hw=arm64
if [ "$NEPI_HW" == "JETSON" ]; then
  arch_hw=arm64
fi
if [ "$NEPI_HW" == "ARM" ]; then
  arch_hw=arm64
fi
if [ "$NEPI_HW" == "AMD" ]; then
  arch_hw=amd64
fi
if [ "$NEPI_HW" == "RPI" ]; then
  arch_hw=rpi
fi
export NEPI_ARCH=$arch_hw

# NEED TO: Set to $NEPI_DOCKER_CONFIG_PATH from ???
export NEPI_DOCKER_CONFIG_FOLDER=/mnt/nepi_config/docker_config
export NEPI_DOCKER_CONFIG_FILE=${NEPI_DOCKER_CONFIG_FOLDER}/nepi_docker_config.yaml
export NEPI_DOCKER_COMPOSE_FILE=${NEPI_DOCKER_CONFIG_FOLDER}/nepi_docker_compose.yml

## NEED TO: Read these from nepi_config.yaml file
export ACTIVE_CONT=nepi_fs_a
export ACTIVE_VERSION=3p2p0-RC2
export ACTIVE_UPLOAD_DATE=0
export ACTIVE_TAG=jetson-3p2p0-rc2
export ACTIVE_ID=0

export INACTIVE_CONT=nepi_fs_b
export INACTIVE_VERSION=uknown
export INACTIVE_UPLOAD_DATE=0
export INACTIVE_TAG=jetson-uknown
export INACTIVE_ID=0

export STAGING_CONT=nepi_staging

export IMPORT_PATH=/media/nepidev/NServer_Backup
export EXPORT_PATH=/mnt/nepi_storage/nepi_full_img_archive

######  NEED TO: Update from current docker status
export RUNNING_CONT=None
export RUNNING_VERSION=uknown
export RUNNING_TAG=uknown
export RUNNING_ID=0

export NEPI_REMOTE_SETUP=1

#### Update Help Test
HELPN="${HELPN}

### NEPI DOCKER CONFIG

NEPI_HW=${NEPI_HW}
NEPI_ARCH=${NEPI_ARCH}
NEPI_DOCKER_CONFIG_FOLDER=${NEPI_DOCKER_CONFIG_FOLDER}
NEPI_DOCKER_CONFIG_FILE=${NEPI_DOCKER_CONFIG_FILE}
NEPI_DOCKER_COMPOSE_FILE=${NEPI_DOCKER_COMPOSE_FILE}

ACTIVE_CONT=${ACTIVE_CONT}
ACTIVE_VERSION-eq${ACTIVE_VERSION}
ACTIVE_TAG=${ACTIVE_TAG}
ACTIVE_ID=${ACTIVE_ID}

INACTIVE_CONT=${INACTIVE_CONT}
INACTIVE_VERSION=${INACTIVE_VERSION}
INACTIVE_TAG=${INACTIVE_TAG}
INACTIVE_ID=${INACTIVE_ID}

STAGING_CONT=${STAGING_CONT}
IMPORT_PATH=${IMPORT_PATH}
EXPORT_PATH=${EXPORT_PATH}

RUNNING_CONT=${RUNNING_CONT}
RUNNING_VERSION=${RUNNING_VERSION}
RUNNING_TAG=${RUNNING_TAG}
RUNNING_ID=${RUNNING_ID}"


# Function to update aliases from config file call same function when changes are made to the onfig file
function refresh_variables(){
  #export NEPI_HW=JETSON
  read_yaml_value "NEPI_HW" "NEPI_HW" "$NEPI_DOCKER_CONFIG_FILE"
  #echo $NEPI_HW

  #export NEPI_ARCH=$arch_hw
  read_yaml_value "NEPI_ARCH" "NEPI_ARCH" "$NEPI_DOCKER_CONFIG_FILE"
  #echo $NEPI_ARCH

  #export ACTIVE_CONT=nepi_fs_a
  read_yaml_value "ACTIVE_CONT" "ACTIVE_CONT" "$NEPI_DOCKER_CONFIG_FILE"
  #echo $ACTIVE_CONT
  #export ACTIVE_VERSION=3p2p0-RC2
  read_yaml_value "ACTIVE_VERSION" "ACTIVE_VERSION" "$NEPI_DOCKER_CONFIG_FILE"
  #echo $ACTIVE_VERSION
  #export ACTIVE_UPLOAD_DATE=0
  read_yaml_value "ACTIVE_UPLOAD_DATE" "ACTIVE_UPLOAD_DATE" "$NEPI_DOCKER_CONFIG_FILE"
  #echo $ACTIVE_UPLOAD_DATE
  #export ACTIVE_TAG=jetson-3p2p0-rc2
  read_yaml_value "ACTIVE_TAG" "ACTIVE_TAG" "$NEPI_DOCKER_CONFIG_FILE"
  #echo $ACTIVE_TAG
  #export ACTIVE_ID=0
  read_yaml_value "ACTIVE_ID" "ACTIVE_ID" "$NEPI_DOCKER_CONFIG_FILE"
  #echo $ACTIVE_ID

  #export INACTIVE_CONT=nepi_fs_b
  read_yaml_value "INACTIVE_CONT" "INACTIVE_CONT" "$NEPI_DOCKER_CONFIG_FILE"
  #echo $INACTIVE_CONT
  #export INACTIVE_VERSION=uknown
  read_yaml_value "INACTIVE_VERSION" "INACTIVE_VERSION" "$NEPI_DOCKER_CONFIG_FILE"
  #echo $INACTIVE_VERSION
  #export INACTIVE_UPLOAD_DATE=0
  read_yaml_value "INACTIVE_UPLOAD_DATE" "INACTIVE_UPLOAD_DATE" "$NEPI_DOCKER_CONFIG_FILE"
  #echo $INACTIVE_UPLOAD_DATE
  #export INACTIVE_TAG=jetson-uknown
  read_yaml_value "INACTIVE_TAG" "INACTIVE_TAG" "$NEPI_DOCKER_CONFIG_FILE"
  #echo $INACTIVE_TAG
  #export INACTIVE_ID=0
  read_yaml_value "INACTIVE_ID" "INACTIVE_ID" "$NEPI_DOCKER_CONFIG_FILE"
  #echo $INACTIVE_ID
  #export STAGING_CONT=nepi_staging
  read_yaml_value "STAGING_CONT" "STAGING_CONT" "$NEPI_DOCKER_CONFIG_FILE"
  #echo $STAGING_CONT

  #STAGING_CONT: nepi_staging
  read_yaml_value "STAGING_CONT" "STAGING_CONT" "$NEPI_DOCKER_CONFIG_FILE"
  #echo $STAGING_CONT
  #IMPORT_PATH: /media/nepidev/NServer_Backup
  read_yaml_value "IMPORT_PATH" "IMPORT_PATH" "$NEPI_DOCKER_CONFIG_FILE"
  #echo $IMPORT_PATH
  #EXPORT_PATH: /mnt/nepi_storage/nepi_full_img
  read_yaml_value "EXPORT_PATH" "EXPORT_PATH" "$NEPI_DOCKER_CONFIG_FILE"
  #echo $EXPORT_PATH


  ######  NEED TO: Update from current docker status
  #export RUNNING_CONT=None
  read_yaml_value "RUNNING_CONT" "RUNNING_CONT" "$NEPI_DOCKER_CONFIG_FILE"
  #echo $RUNNING_CONT
  #export RUNNING_VERSION=uknown
  read_yaml_value "RUNNING_VERSION" "RUNNING_VERSION" "$NEPI_DOCKER_CONFIG_FILE"
  #echo $RUNNING_VERSION
  #export RUNNING_TAG=uknown
  read_yaml_value "RUNNING_TAG" "RUNNING_TAG" "$NEPI_DOCKER_CONFIG_FILE"
  #echo $RUNNING_TAG
  #export RUNNING_ID=0
  read_yaml_value "RUNNING_ID" "RUNNING_ID" "$NEPI_DOCKER_CONFIG_FILE"
  #echo $RUNNING_ID

  #export NEPI_REMOTE_SETUP=1
  read_yaml_value "NEPI_REMOTE_SETUP" "NEPI_REMOTE_SETUP" "$NEPI_DOCKER_CONFIG_FILE"
  #echo $NEPI_REMOTE_SETUP


}

#############################
# NEPI DOCKER FUNCTIONS
#############################

######################
# IMPORT_NEPI
######################

function create_tag(){
    HW_NAME=$1
    SW_VERSION=$2
    tag=${HW_NAME}-${SW_VERSION}
    ltag=sed -e 's/\(.*\)/\L\1/' <<< "$tag"
    echo "$ltag"
}
export -f create_tag

function import_nepi(){
  refresh_variables
  IMPORT_PATH=$IMPORT_PATH
  echo $IMPORT_PATH
  ###### NEED TO GET LIST OF AVAILABLE TARS and Select Image
  #IMAGE_FILE=nepi-jetson-3p2p0-rc2.tar
  IMAGE_FILE=TEST.tar
  echo $IMAGE_FILE
  ######  NEED TO: Update from IMPORT_PATH tar file
  IMAGE_VERSION=3p2p0
  echo $IMAGE_VERSION
  ######
  #INSTALL_IMAGE=${IMPORT_PATH}/${IMAGE_FILE}
  INSTALL_IMAGE=${EXPORT_PATH}/''${IMAGE_FILE}
  echo $INSTALL_IMAGE
  #1) Stop any processes for INACTIVE_CONT
  #docker stop ${RUNNING_CONT}
  #2) Import INSTALL_IMAGE to STAGING_CONT
  res=$(sudo docker import $INSTALL_IMAGE)
  echo $res
  #3) Remove INACTIVE_CONT
  #docker stop ${ACTIVE_CONT}
  #4) Rename STAGING_CONT to INACTIVE_CONT
  hash=${res##*sha256:}
  echo $hash
  ID=${hash:0:12}
  echo $ID
  NEW_DATE=$(date +%Y-%m-%d)
  echo $NEW_DATE
  NEW_NAME=$INACTIVE_CONT
  echo $NEW_NAME
  NEW_TAG=$INACTIVE_TAG
  echo $NEW_TAG
  NEW_VERSION=$IMAGE_VERSION
  echo $NEW_VERSION
  sudo docker tag $ID ${NEW_NAME}:${NEW_TAG}
  #6) Update inactive version,tags,ids in nepi_docker_config.yaml
  update_yaml_value "INACTIVE_VERSION" "$INACTIVE_VERSION" "$NEPI_DOCKER_CONFIG_FILE"
  update_yaml_value "INACTIVE_UPLOAD_DATE" "$NEW_DATE" "$NEPI_DOCKER_CONFIG_FILE"
  update_yaml_value "INACTIVE_TAG" "$NEW_TAG" "$NEPI_DOCKER_CONFIG_FILE"
  update_yaml_value "INACTIVE_ID" "$NEW_VERSION" "$NEPI_DOCKER_CONFIG_FILE"
  echo "  ADD SOME PRINT OUTS  "
  refresh_variables
}
export -f import_nepi

######################
# IMPORT_NEPI
######################

function export_nepi(){
  refresh_variables
  if ["$RUNNING_CONT" != "None"]; then
    TAR_EXPORT_PATH=${EXPORT_PATH}/''${RUNNING_CONT}-backup.tar
    #echo $TAR_EXPORT_PATH
    sudo docker export 800d94b64134 > $TAR_EXPORT_PATH
  else
    echo "No Running Container"
  fi

}
export -f export_nepi


######################
# SWITCH_NEPI
######################
function switch_nepi(){
  
  refresh_variables
  
  #5) Switch active/inactive containers in nepi_docker_config.yaml 
  #6) Update active/inactive version,tags,ids in nepi_docker_config.yaml
  #7) Update Docker Compose
  
  ### SET INACTIVE DATA AS ACTIVE DATA
  update_yaml_value ACTIVE_CONT "$INACTIVE_CONT" $NEPI_DOCKER_CONFIG_FILE
  update_yaml_value "ACTIVE_VERSION" "$INACTIVE_VERSION" "$NEPI_DOCKER_CONFIG_FILE"
  update_yaml_value "ACTIVE_UPLOAD_DATE" "$INACTIVE_UPLOAD_DATE" "$NEPI_DOCKER_CONFIG_FILE"
  update_yaml_value "ACTIVE_TAG" "$INACTIVE_TAG" "$NEPI_DOCKER_CONFIG_FILE"
  update_yaml_value "ACTIVE_ID" "$INACTIVE_ID" "$NEPI_DOCKER_CONFIG_FILE"

  ### SET ACTIVE DATA AS INACTIVE DATA
  update_yaml_value "INACTIVE_CONT" "$ACTIVE_CONT" "$NEPI_DOCKER_CONFIG_FILE"
  update_yaml_value "INACTIVE_VERSION" "$ACTIVE_VERSION" "$NEPI_DOCKER_CONFIG_FILE"
  update_yaml_value "INACTIVE_UPLOAD_DATE" "$ACTIVE_UPLOAD_DATE" "$NEPI_DOCKER_CONFIG_FILE"
  update_yaml_value "INACTIVE_TAG" "$ACTIVE_TAG" "$NEPI_DOCKER_CONFIG_FILE"
  update_yaml_value "INACTIVE_ID" "$ACTIVE_ID" "$NEPI_DOCKER_CONFIG_FILE"
  
}
export -f switch_nepi

######################
# RUN_NEPI
######################
function run_nepi(){
    #Run NEPI Complete
    sudo docker run --rm --privileged -e UDEV=1 --user nepi --gpus all \
    --mount type=bind,source=/mnt/nepi_storage,target=/mnt/nepi_storage \
    --mount type=bind,source=/dev,target=/dev \
    -it --net=host --runtime nvidia -e DISPLAY=$DISPLAY \
    -v /tmp/.X11-unix/:/tmp/.X11-unix \
    ${ACTIVE_CONT}:${ACTIVE_TAG} /bin/bash \
    -c "/nepi_engine_start.sh"
}
export -f run_nepi

######################
# LOGIN_NEPI
######################
function login_nepi(){
    # Connect to a Running Container
    sudo docker exec -it ${ACTIVE_ID} /bin/bash
}
export -f login_nepi



######################
# RUN_DEV
######################
function run_dev(){
    #Run NEPI in Dev Mode
    sudo docker run --privileged -e UDEV=1 --user nepi --gpus all \
    --mount type=bind,source=/mnt/nepi_storage,target=/mnt/nepi_storage \
    --mount type=bind,source=/dev,target=/dev \
    -it --net=host --runtime nvidia \
    -v /tmp/.X11-unix/:/tmp/.X11-unix \
    ${ACTIVE_CONT}:${ACTIVE_TAG} /bin/bash
}
export -f run_dev


######################
# STOP_DEV
######################
function stop_dev(){
    yq e '.NEPI_HW' nepi_docker_config.yaml
}
export -f stop_dev

######################
# START_DEV
######################
function start_dev(){

}
export -f start_dev

######################
# RESTART_DEV
######################
function restart_dev(){

}
export -f restart_dev

######################
# EXPORT_DEV
######################
function export_dev(){

}
export -f export_dev

######################
# READ_DOCKER_CONFIG
######################
function ffile(){
    yq e -i '.' nepi_docker_config.yaml 
}
export -f ffile

###################################
#NEPI folder shortcuts
###################################
export DRIVE="/mnt/nepi_storage"

export AI="/mnt/nepi_storage/ai_models"
export AUTO="/mnt/nepi_storage/automation_scripts"
export DATA="/mnt/nepi_storage/data"
export INSTALL="/mnt/nepi_storage/intstall"
export NFI="/mnt/nepi_storage/nepi_full_img"
export NFIA="/mnt/nepi_storage/nepi_full_img_archive"
export SRC="/mnt/nepi_storage/nepi_src/nepi_engine_ws/src"
export SRCRUI="/mnt/nepi_storage/nepi_src/nepi_engine_ws/src/nepi_rui/src/rui_webserver/rui-app/src"
export TMP="/mnt/nepi_storage/tmp"

export FCFG="/mnt/nepi_config/factory_cfg"
export SCFG="/mnt/nepi_config/system_cfg"
export UCFG="/mnt/nepi_storage/user_cfg"

# NEPI navigation shortcuts
alias drive="cd $DRIVE"

alias ai="cd $AI"
alias aif="cd $AIF"
alias auto="cd $AUTO"
alias data="cd $DATA"
alias intstall="cd $INSTALL"
alias nfi="cd $NFI"
alias nfia="cd $NFIA"
alias src="cd $SRC"
alias srcrui="cd $SRCRUI"
alias tmp="cd $TMP"
alias train="cd $TRAIN"


alias fcfg="cd $FCFG"
alias scfg="cd $SCFG"
alias ucfg="cd $UCFG"



# Print out the nepi shortcuts
function helpn(){
    HELPN="${HELPN}

${UINFO}

################################
## NEPI folder shortcuts ##
################################
drive = /mnt/nepi_storage

ai = /mnt/nepi_storage/ai_models
auto = /mnt/nepi_storage/automation_scripts
data = /mnt/nepi_storage/data
intstall = /mnt/nepi_storage/intstall
nfi = /mnt/nepi_storage/nepi_full_img
nfia = /mnt/nepi_storage/nepi_full_img_archive
src = /mnt/nepi_storage/nepi_src/nepi_engine_ws/src
srcrui = /mnt/nepi_storage/nepi_src/nepi_engine_ws/src/nepi_rui/src/rui_webserver/rui-app/src
tmp = /mnt/nepi_storage/tmp

fcfg = /mnt/nepi_config/factory_cfg
scfg = /mnt/nepi_config/system_cfg
ucfg = /mnt/nepi_storage/user_cfg
"
    echo "$HELPN"
}



