####################################################
### RUN-TIME CONFIGURABLE SETTINGS
####################################################
# NEPI ENVIRONMENT CONFIG
NEPI_DEVICE_ID: device1
NEPI_IP: 192.168.179.103
NEPI_NTP_IP: 192.168.179.5
NEPI_DHCP_ON_START: 0

####################################################
### INSTALL-TIME CONFIGURABLE SETTINGS
####################################################
# NEPI PARTITION CONFIG
# It is recommended that these folders be create as their own partitions
# so that these files are not affected by any device file system changes
# NEPI Docker Folder
# Set to DOCKER to use dockers native docker image storage location
# Set to custom path to configure a custom docker image storage loacation
NEPI_DOCKER: /mnt/nepi_docker
DOCKER_MIN_GB: 100
# NEPI Storage and Config Folders
NEPI_STORAGE: /mnt/nepi_storage
STORAGE_MIN_GB: 250
NEPI_CONFIG: /mnt/nepi_config
CONFIG_MIN_GB: 1
####################################################
# NEPI MANAGED SERVICES Config
# NEPI Managed Resources. Set to 0 to turn off NEPI management of this resource
# Note, if enabled for a docker deployment, 
# these system services will be managed in the NEPI HOST OS environment,
# and HOST OS /etc files will be overwitten.
NEPI_MANAGES_NETWORK: 1
NEPI_MANAGES_TIME: 1
NEPI_MANAGES_SSH: 1
# If not enabled, proper HOST service configurations must be done manually.
# -NETWORK-Ensure on the Host OS that the NEPI_IP address enabled as a static ip address
# -NETWORK-Setup and Enable DHCP Client for internet connections if needed
# -TIME-Setup and configure Chrony time management service
# -TIME-Configure Chrony's NTP service to listen for the NEPI_NTP_IP address
# -SSH-Configure the SSH credentials and SSH requried conf files

####################################################
### BUILD-TIME CONFIGURABLE SETTINGS
####################################################
# NEPI USER
NEPI_USER: nepi
NEPI_USER_PW: nepi
NEPI_ADMIN: nepiadmin
NEPI_ADMIN_PW: nepiadmin
####################################################
# NEPI HARDWERE CONFIG
# NEPI Hardware Host Options: JETSON,RPI,ARM64,AMD64
NEPI_HW_TYPE: JETSON
# NEPI Hardware Host Model Options: ORIN, XAVIER, TX2, NANO, RPI4, GENERIC
NEPI_HW_MODEL: ORIN
####################################################
# NEPI FS PARTITION SETINGS  
NEPI_AB_FS: 1
NEPI_IN_CONTAINER: 1
# Set to partition path if running directly on device's file system
# Or "CONTAINER" if running in a docker container
NEPI_BOOT_DEVICE: CONTAINER
NEPI_FS_DEVICE: CONTAINER
NEPI_STORAGE_DEVICE: CONTAINER
####################################################
# NEPI SOFTWARE Config
NEPI_PYTHON: 3.8
NEPI_ROS: NOETIC
NEPI_HAS_CUDA: 1
NEPI_CUDA_VERSION: 11.8
NEPI_HAS_XPU: 0
####################################################
# NEPI FOLDERS CONFIG
# NEPI Folders
NEPI_SOURCE: /home/nepidev
NEPI_ENV: nepi_env
NEPI_HOME: /home/nepi
NEPI_BASE: /opt/nepi
NEPI_RUI: /opt/nepi/nepi_rui
NEPI_ENGINE: /opt/nepi/nepi_engine
NEPI_ETC: /opt/nepi/etc
NEPI_SCRIPTS: /opt/nepi/scripts
# NEPI Config Paths
NEPI_DOCKER_CONFIG: /mnt/nepi_config/docker_cfg
NEPI_FACTORY_CONFIG: /mnt/nepi_config/factory_cfg
NEPI_SYSTEM_CONFIG: /mnt/nepi_config/system_cfg
NEPI_USR_CONFIG: /mnt/nepi_storage/user_cfg
# NEPI Image Paths
NEPI_IMPORT_PATH: /mnt/nepi_storage/nepi_images
NEPI_EXPORT_PATH: /mnt/nepi_storage/nepi_images



