#! /bin/bash
##
## Copyright (c) 2024 Numurus, LLC <https://www.numurus.com>.
##
## This file is part of nepi-engine
## (see https://github.com/nepi-engine).
##
## License: 3-clause BSD, see https://opensource.org/licenses/BSD-3-Clause
##

# Start NEPI Time Management Processes
if [[ -v NEPI_MANAGES_TIME ]]; then
  if [[ "$NEPI_MANAGES_TIME" -eq 1 ]]; then
    echo "Starting NEPI Time Management Services."
    if [[ "NEPI_IN_CONTAINER" -eq 0 ]]; then
      sudo /usr/sbin/chronyd
    fi
  else
    echo "NEPI Time Management Disabled."
  fi

else
  echo "NEPI Time Management Disabled."
fi

