#! /bin/bash
##
## Copyright (c) 2024 Numurus, LLC <https://www.numurus.com>.
##
## This file is part of nepi-engine
## (see https://github.com/nepi-engine).
##
## License: 3-clause BSD, see https://opensource.org/licenses/BSD-3-Clause
##

refresh_nepi_config

# Start NEPI DHCP process
ENABLE_DHCP=1
if [ -v ENABLE_NEPI_DHCP ]; then
  ENABLE_DHCP=$ENABLE_NEPI_DHCP
elif [ -v NEPI_DHCP_ON_START ]; then
   ENABLE_DHCP=$NEPI_DHCP_ON_START
fi

if [ "$ENABLE_DHCP" -eq 1 ]; then
  if [ -v NEPI_MANAGES_NETWORK ]; then
    if [ "$NEPI_MANAGES_NETWORK" -eq 1 ]; then
      echo "Enabling NEPI DHCP."
    if [[ "NEPI_IN_CONTAINER" -eq 0 ]]; then
      sudo dhclient -nw
    fi
    else
      echo "NEPI Network Management Disabled."
    fi

  else
    echo "NEPI Network Management Disabled."
  fi
fi


